Configurations:
  - FilesAndFolders
  - RegistryValues

FilesAndFolders:
  Items:
    - DestinationPath: C:\Test
      Type: Directory
    - DestinationPath: C:\Test\Test1File1.txt
      Type: File
      Contents: Some test data
      DependsOn: '[File]C\Test'
    - DestinationPath: C:\Test\Test1File2.txt
      Type: File
      Contents: Some test data
      DependsOn: '[File]C\Test'
    - DestinationPath: C:\GpoBackup
      SourcePath: \\DSCDC01\SYSVOL\contoso.com\Policies
      Type: Directory

RegistryValues:
  Values:
    - Key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Parameters
      ValueName: NtpServer
      ValueData: pool.ntp.org,0x9
      ValueType: String
      Ensure: Present
      Force: true

SecurityBaseline:
  Role: FileServer