Configurations:
  - SecurityBase
  - WindowsFeatures
  - NetworkIpConfiguration
  - ChocolateyPackages

WindowsFeatures:
  Name:
    - -Telnet-Client

SecurityBase:
  Role: Baseline

NetworkIpConfiguration:
  Prefix: 24
  Gateway: 192.168.111.50
  DnsServer: 192.168.111.10
  InterfaceAlias: Ethernet
  DisableNetbios: True

ChocolateyPackages:
  Package:
  - Name: winrar
    Ensure: Present
    Version: '5.90.0.20200401'
    Credential: '[ENC=PE9ianMgVmVyc2lvbj0iMS4xLjAuMSIgeG1sbnM9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vcG93ZXJzaGVsbC8yMDA0LzA0Ij4NCiAgPE9iaiBSZWZJZD0iMCI+DQogICAgPFROIFJlZklkPSIwIj4NCiAgICAgIDxUPlN5c3RlbS5NYW5hZ2VtZW50LkF1dG9tYXRpb24uUFNDdXN0b21PYmplY3Q8L1Q+DQogICAgICA8VD5TeXN0ZW0uT2JqZWN0PC9UPg0KICAgIDwvVE4+DQogICAgPE1TPg0KICAgICAgPE9iaiBOPSJLZXlEYXRhIiBSZWZJZD0iMSI+DQogICAgICAgIDxUTiBSZWZJZD0iMSI+DQogICAgICAgICAgPFQ+U3lzdGVtLk9iamVjdFtdPC9UPg0KICAgICAgICAgIDxUPlN5c3RlbS5BcnJheTwvVD4NCiAgICAgICAgICA8VD5TeXN0ZW0uT2JqZWN0PC9UPg0KICAgICAgICA8L1ROPg0KICAgICAgICA8TFNUPg0KICAgICAgICAgIDxPYmogUmVmSWQ9IjIiPg0KICAgICAgICAgICAgPFROUmVmIFJlZklkPSIwIiAvPg0KICAgICAgICAgICAgPE1TPg0KICAgICAgICAgICAgICA8UyBOPSJIYXNoIj5ENzE4MTg4OTJEOTIxNjMwMzM4MkFEQkE3NEFEOTFFOTVDOTU4RjdGQTEyQ0Q4MEJGMEQzN0NDQUZCREE5MTE2PC9TPg0KICAgICAgICAgICAgICA8STMyIE49Ikl0ZXJhdGlvbkNvdW50Ij41MDAwMDwvSTMyPg0KICAgICAgICAgICAgICA8QkEgTj0iS2V5Ij5iSWxFbGd4RTlYaER6N3gxT3Qya2RLT2ZDWkM2RFNxRlVpREtDUVBPYmJCYTlaY1l6TXI2dGRKcHZwRE5vTU5nPC9CQT4NCiAgICAgICAgICAgICAgPEJBIE49Ikhhc2hTYWx0Ij5EU1BYVm1jSklkbGFHMnRrQ2xrUlBvSW45cmhGOEZtVzZFVTN5eTRtRFhrPTwvQkE+DQogICAgICAgICAgICAgIDxCQSBOPSJTYWx0Ij5HUUluU2J1OThQaUZwMmNMeWdDeW0zeXRYYVZQMlVhdkNqQjhPcHlNTEJJPTwvQkE+DQogICAgICAgICAgICAgIDxCQSBOPSJJViI+YmV5b0ZOeVpRQzV1R3lMZ1dQZmhsZ0tScEJyL204bHFWc3UrMUdkaTNFZz08L0JBPg0KICAgICAgICAgICAgPC9NUz4NCiAgICAgICAgICA8L09iaj4NCiAgICAgICAgPC9MU1Q+DQogICAgICA8L09iaj4NCiAgICAgIDxCQSBOPSJDaXBoZXJUZXh0Ij54dy90WGh0UFp3MEF6anlmL1JkRW1QYVg1ZUNDWS9hS3pqQmwzd0dHck14K2pIT0VpVXpORGdjdk9ScGd4Q1FuTWMzQ1g5dnlNWlhPWmNXVjRjOWZ2UT09PC9CQT4NCiAgICAgIDxCQSBOPSJITUFDIj5uK1lYS0ZQdzU1Q3orN0F0cWRrQUpIUUxQTjdYaEE3K2k4V3k2ZDg1OTBFPTwvQkE+DQogICAgICA8UyBOPSJUeXBlIj5TeXN0ZW0uTWFuYWdlbWVudC5BdXRvbWF0aW9uLlBTQ3JlZGVudGlhbDwvUz4NCiAgICA8L01TPg0KICA8L09iaj4NCjwvT2Jqcz4=]'
    ChocolateyOptions:
      Source: Software
