Configurations:
  - WindowsServices
  - RegistryValues
  - FilesAndFolders
  - WebApplicationPools
  - WebApplications

FilesAndFolders:
  Items:
    - DestinationPath: C:\Inetpub\TestApp1
      Type: Directory
    - DestinationPath: C:\Inetpub\TestApp2
      Type: Directory
    - DestinationPath: C:\Inetpub\TestApp1\default.html
      Type: File
      Contents: This is TestApp1
      DependsOn: '[File]file_C__Inetpub_TestApp1'
    - DestinationPath: C:\Inetpub\TestApp2\default.html
      Type: File
      Contents: This is TestApp2
      DependsOn: '[File]file_C__Inetpub_TestApp2'

WebApplicationPools:
  Items:
    - Name: TestAppPool1
      Ensure: Present
      IdentityType: ApplicationPoolIdentity
      State: Started
    - Name: TestAppPool2
      Ensure: Present
      IdentityType: ApplicationPoolIdentity
      State: Started
  
WebApplications:
  Items:
    - Name: TestApp1
      PhysicalPath: C:\Inetpub\TestApp1
      WebAppPool: TestAppPool1
      Website: Default Web Site
      Ensure: Present
    - Name: TestApp2
      PhysicalPath: C:\Inetpub\TestApp2
      WebAppPool: TestAppPool2
      Website: Default Web Site
      Ensure: Present

RegistryValues:
    Values:
    - Key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Parameters
      ValueName: NtpServer
      ValueData: time.windows.com,0x9;
      ValueType: String
      Ensure: Present
      Force: true

SecurityBase:
  Role: WebServer

WindowsFeatures:
  Name:
  - +Web-Server
  - -WoW64-Support

WindowsServices:
  Services:
    - Name: FileDummy
      DisplayName: Dummy Service on Web Servers
      StartupType: Automatic
      Path: C:\DummyService.exe

DscTagging:
  Layers:
    - Roles\WebServer
